/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.management.system;

import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ESCJAVA04202228
 */
public class EmployeeManage extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeManage
     */
    public EmployeeManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmpId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Design = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        EmpType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        EmpSex = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        EmpAcc = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpAdd = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        EmpMob = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EmpMail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EmpBankAcc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Empifsc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        EmpSal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        EmpAllw = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        EmpSplAll = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EmpHRA = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        EmpLocal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        EmpBaskAl = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Emppf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        EmpESI = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        EmpAditionalIns = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        EmpGross = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        EmpPerSal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SaveAction = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        EmpLastDt = new com.toedter.calendar.JDateChooser();
        EmpJoinDt = new com.toedter.calendar.JDateChooser();
        EmpName1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employees");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 165, -1));

        jLabel2.setText("Employee Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        EmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIdActionPerformed(evt);
            }
        });
        getContentPane().add(EmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));

        jLabel3.setText("Employee ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, 20));

        jLabel4.setText("Designation");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        Design.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sales Man", "Accountant", "Team Leader", "Security" }));
        getContentPane().add(Design, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, -1));

        jLabel5.setText("Employee Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        EmpType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanent", "Temporary" }));
        getContentPane().add(EmpType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, -1));

        jLabel6.setText("Sex");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        EmpSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Transgender" }));
        getContentPane().add(EmpSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, -1));

        jLabel7.setText("Account");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        EmpAcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salary Account", "Other Account" }));
        getContentPane().add(EmpAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, -1));

        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        EmpAdd.setColumns(20);
        EmpAdd.setRows(5);
        jScrollPane1.setViewportView(EmpAdd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 220, 80));

        jLabel9.setText("Mob No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 50, 20));
        getContentPane().add(EmpMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 220, -1));

        jLabel10.setText("Email ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 50, 20));
        getContentPane().add(EmpMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 220, 20));

        jLabel11.setText("Bank Account No.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        EmpBankAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpBankAccActionPerformed(evt);
            }
        });
        getContentPane().add(EmpBankAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 190, -1));

        jLabel12.setText("IFSC Code");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 60, 20));
        getContentPane().add(Empifsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 220, -1));

        jLabel13.setText("Basic Salary");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));
        getContentPane().add(EmpSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 120, -1));

        jLabel14.setText("Allowance");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 60, 20));
        getContentPane().add(EmpAllw, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 120, -1));

        jLabel15.setText("Special Allowance");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 100, -1));
        getContentPane().add(EmpSplAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 110, -1));

        jLabel16.setText("HRA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 30, 20));
        getContentPane().add(EmpHRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 120, -1));

        jLabel17.setText("Local Conv.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));
        getContentPane().add(EmpLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 120, -1));

        jLabel18.setText("Basket Allow.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, -1, -1));

        EmpBaskAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpBaskAlActionPerformed(evt);
            }
        });
        getContentPane().add(EmpBaskAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 120, -1));

        jLabel19.setText("PF Deducation");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 80, 20));
        getContentPane().add(Emppf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 110, -1));

        jLabel20.setText("ESI Deducation");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, -1, -1));
        getContentPane().add(EmpESI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, 110, -1));

        jLabel21.setText("Aditional Ins.");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, -1, -1));
        getContentPane().add(EmpAditionalIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 110, -1));

        jLabel22.setText("Gross Salary");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, -1, -1));
        getContentPane().add(EmpGross, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 110, -1));

        jLabel23.setText("Per Day Salary");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));
        getContentPane().add(EmpPerSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 110, -1));

        jLabel24.setText("Emp Join Date");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, 20));

        jLabel25.setText("Emp Last Date");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 80, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Designation", "Employee Type", "Sex", "Account", "Address", "Mob No.", "Email ID", "Bank Account No.", "IFSC Code", "Basic Salary", "Allowance", "Special Allowance", "HRA", "Local Conv.", "Basket Allow.", "Aditional Ins.", "PF Deducation", "ESI Deducation", "Gross Salary", "Per Day Salary", "Employee Join Date", "Employee Last Date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1360, 290));

        SaveAction.setText("Save");
        SaveAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionActionPerformed(evt);
            }
        });
        getContentPane().add(SaveAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jButton2.setText("Modify");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, -1, -1));

        jButton3.setText("Delete");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, -1, -1));

        jLabel26.setText("Employee Name");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 710, -1, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 710, 180, -1));

        jButton4.setText("Search");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, -1, -1));

        jButton5.setText("PDF");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 710, -1, -1));

        jButton6.setText("EXCEL");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, -1, -1));

        jButton7.setText("PRINT");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, -1, -1));
        getContentPane().add(EmpLastDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, -1, -1));
        getContentPane().add(EmpJoinDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, -1, -1));

        EmpName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpName1ActionPerformed(evt);
            }
        });
        getContentPane().add(EmpName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpBankAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpBankAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpBankAccActionPerformed

    private void EmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIdActionPerformed

    private void EmpBaskAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpBaskAlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpBaskAlActionPerformed

    private void SaveActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionActionPerformed
        String employeeName = EmpId.getText();
        String empId = EmpId.getName();
        String designation = (String) Design.getSelectedItem();
        String empType = (String) EmpType.getSelectedItem();
        String empSex = (String) EmpSex.getSelectedItem();
        String Account = (String) EmpAcc.getSelectedItem();
        String empAddress = EmpAdd.getText();
        String mobile = EmpMob.getText();
        String email = EmpMail.getText();
        String accountNo = EmpBankAcc.getText();
        String ifsc = Empifsc.getText();
        String basicSalary = EmpSal.getText();
        String allowance = EmpAllw.getText();
        String specialAllowance = EmpSplAll.getText();
        String hra = EmpHRA.getText();
        String localConv = EmpLocal.getText();
        String basketAllowance = EmpBaskAl.getText();
        String additionalIns = EmpAditionalIns.getText();
        String pf = Emppf.getText();
        String esi = EmpESI.getText();
        String grossSalary = EmpGross.getText();
        String perDaySalary = EmpPerSal.getText();

// Assuming this.empJoinDate returns a Date object
        Date empJoinDate = this.EmpJoinDt.getDate();
        Date empLastDate = this.EmpLastDt.getDate();

// Create a SimpleDateFormat to format the date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Employee (empId, empName, designation, empType, empSex, empAccount, empAddress, mobile, email, accountno, ifsc, basicSalary, allowance, specialAllowance, hra, localConv, basketAllowance, additionalIns, pf, esi, grossSalary, perdaysalary, joindate, lastdate) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

            ps.setString(1, empId);
            ps.setString(2, employeeName);
            ps.setString(3, designation);
            ps.setString(4, empType);
            ps.setString(5, empSex);
            ps.setString(6, Account);
            ps.setString(7, empAddress);
            ps.setString(8, mobile);
            ps.setString(9, email);
            ps.setString(10, accountNo);
            ps.setString(11, ifsc);
            ps.setString(12, basicSalary);
            ps.setString(13, allowance);
            ps.setString(14, specialAllowance);
            ps.setString(15, hra);
            ps.setString(16, localConv);
            ps.setString(17, basketAllowance);
            ps.setString(18, additionalIns);
            ps.setString(19, pf);
            ps.setString(20, esi);
            ps.setString(21, grossSalary);
            ps.setString(22, perDaySalary);
            ps.setString(23, sdf.format(empJoinDate));
            ps.setString(24, sdf.format(empLastDate));

            int rowsInserted = ps.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Data Saved Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to save data. Please try again.");
            }

            con.close(); // Close the connection when done.
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_SaveActionActionPerformed

    private void EmpName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Design;
    private javax.swing.JComboBox<String> EmpAcc;
    private javax.swing.JTextArea EmpAdd;
    private javax.swing.JTextField EmpAditionalIns;
    private javax.swing.JTextField EmpAllw;
    private javax.swing.JTextField EmpBankAcc;
    private javax.swing.JTextField EmpBaskAl;
    private javax.swing.JTextField EmpESI;
    private javax.swing.JTextField EmpGross;
    private javax.swing.JTextField EmpHRA;
    private javax.swing.JTextField EmpId;
    private com.toedter.calendar.JDateChooser EmpJoinDt;
    private com.toedter.calendar.JDateChooser EmpLastDt;
    private javax.swing.JTextField EmpLocal;
    private javax.swing.JTextField EmpMail;
    private javax.swing.JTextField EmpMob;
    private javax.swing.JTextField EmpName1;
    private javax.swing.JTextField EmpPerSal;
    private javax.swing.JTextField EmpSal;
    private javax.swing.JComboBox<String> EmpSex;
    private javax.swing.JTextField EmpSplAll;
    private javax.swing.JComboBox<String> EmpType;
    private javax.swing.JTextField Empifsc;
    private javax.swing.JTextField Emppf;
    private javax.swing.JButton SaveAction;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
